const itemList = [
  {
      id: '001',
      src: 'photo/1.jpg',
      rating:{
        star: 4.8 ,
        reviews: 1020
      },
      companyName:"Carlton London",
      itemName:"Rhodium-Plated CZ Floral Studs",
      originalPrice:1045,
      discount:"42% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
    id: '002',
    src: 'photo/2.jpg',
    rating:{
      star: 4.0 ,
      reviews: 100
    },
    companyName:'CUKOO',
    itemName:'Women Padded Halter Neck Swimming Dress',
    originalPrice:1345,
    discount:"62% OFF",
    return_period: 14,
    delivery_date: '10 Oct 2023',
  },
  {
    id: '003',
    src: 'photo/3.jpg',
    rating: {
      star: 4.1,
      reviews: 249,
    },
    companyName: 'NUEVOSDAMAS',
    itemName: 'Women Red & White Printed A-Line Knee-Length Skirts',
      originalPrice: 1599,
      discount:"33% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
      id: '004',
      src: 'photo/4.jpg',
      rating: {
        star: 5.0,
          reviews: 1200,
      },
      companyName: 'ADIDAS',
      itemName: 'Indian Cricket ODI Jersey',
      originalPrice: 999,
      discount: "0% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
      id: '005',
      src: 'photo/5.jpg',
      rating: {
        star: 4.2,
          reviews: 3500,
      },
      companyName: 'Roadster',
      itemName: 'Pure Cotton T-shirt',
      originalPrice: 1399,
      discount:"23% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
      id: '006',
      src: 'photo/6.jpg',
      rating: {
        star: 0.0,
          reviews: 0,
      },
      companyName: 'Nike',
      itemName: 'Men ReactX Running Shoes',
      originalPrice: 14995,
      discount:"34% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
      id: '007',
      src: 'photo/7.jpg',
      rating: {
        star: 4.2,
          reviews: 388,
      },
      companyName: 'The Indian Garage Co',
      itemName: 'Men Slim Fit Regular Shorts',
      originalPrice: 1599,
      discount:"16% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  },
  {
      id: '008',
      src: 'photo/8.jpg',
      rating: {
        star: 4.2,
          reviews: 5200,
      },
      companyName: 'Nivea',
      itemName: 'Men Fresh Deodrant 150ml',
      originalPrice: 285,
      discount:"49% OFF",
      return_period: 14,
      delivery_date: '10 Oct 2023',
  }
];